stages:
  - test
  - build
  - test

# Define the build stage for front end and back end
frontend_build:
  stage: build
  script:
    - cd frontend
    - npm install
    - npm run build
  only:
    - main

backend_build:
  stage: build
  script:
    - cd backend
    - npm install
  only:
    - main
