image: node:20.18.0

stages:
  - test
  - build

# Frontend Test Stage
test_frontend:
  stage: test
  script:
    - cd frontend
    - npm install
    - npm test  
# Backend Test Stage
test_backend:
  stage: test
  script:
    - cd backend
    - npm install
    - npm test  

# Frontend Build Stage
build_frontend:
  stage: build
  script:
    - cd frontend
    - rm -rf node_modules package-lock.json
    - npm ci
  script:
    - npm run build
  artifacts:
    paths:
      - frontend/build  # Save frontend build output as an artifact
  

# Backend Build Stage
build_backend:
  stage: build
  before_script:
    - cd backend
    - rm -rf node_modules package-lock.json
    - npm ci
  script:
    - echo "Backend build completed"

# Frontend Test Job
test-frontend:
  stage: test
  before_script:
    - cd frontend
    - npm ci
  script:
    - cd backend
    - npm install
    - echo "No build necessary for backend"  # No actual build step, just install dependencies
