image: node:20.18.0
stages:
  - build
  - test
  - deploy

frontend_build:
  stage: build
  script:
    - cd frontend
    - npm install  # Installs dependencies for the frontend
    - npm run build  # Optional: Only include if your frontend needs a build step
  only:
    - main

backend_build:
  stage: build
  script:
    - cd backend
    - npm install  # Installs dependencies for the backend
    - npm run build  # Optional: Only include if your backend needs a build step
  only:
    - main
