image: node:20.18.0

stages:
  - build
  - test

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - frontend/node_modules/
    - backend/node_modules/

before_script:
  - npm config set cache /cache --global  # Use CI cache for npm

# Frontend Build Job
build-frontend:
  stage: build
  before_script:
    - cd frontend
    - rm -rf node_modules package-lock.json
    - npm install
  script:
    - npm run build
  artifacts:
    paths:
      - frontend/build
  only:
    - main

# Backend Build Job
build-backend:
  stage: build
  before_script:
    - cd backend
    - rm -rf node_modules package-lock.json
    - npm install
  script:
    - echo "Backend build completed"

# Frontend Test Job
test-frontend:
  stage: test
  before_script:
    - cd frontend
    - npm ci
  script:
    - npm test
  artifacts:
    when: always
    paths:
      - frontend/test-reports

# Backend Test Job
test-backend:
  stage: test
  before_script:
    - cd backend
    - npm ci
  script:
    - npm test
  artifacts:
    when: always
    paths:
      - backend/test-reports
