image: node:20.18.0  # Use Node.js image that matches your project

stages:
  - build
  - test

cache:
  paths:
    - node_modules/
    - frontend/node_modules/
    - backend/node_modules/

# Frontend Build Job
build-frontend:
  stage: build
  script:
    - cd frontend
    - npm install
    - npm run build  # Make sure "build" script is defined in frontend/package.json
    - cd ..
  artifacts:
    paths:
      - frontend

# Backend Build Job
build-backend:
  stage: build
  script:
    - cd backend
    - npm install
    - npm run build  
    - cd ..
  artifacts:
    paths:
      - backend

# Frontend Test Job
test-frontend:
  stage: test
  script:
    - cd frontend
    - npm install  # Ensure dependencies are up-to-date
    - npm test     # Ensure "test" script is defined in frontend/package.json
    - cd ..
  artifacts:
    when: always
    paths:
      - frontend

# Backend Test Job
test-backend:
  stage: test
  script:
    - cd backend
    - npm install  # Ensure dependencies are up-to-date
    - npm test     # Ensure "test" script is defined in backend/package.json
    - cd ..
  artifacts:
    when: always
    paths:
      - backend
